swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /transactions/monthly:
    get:
      tags:
        - Transaction Module
      summary: Récupérer toutes les transactions du mois en cours, groupées par compte
      description: >-
        API pour récupérer toutes les transactions de l'utilisateur pour le mois
        en cours, groupées par compte
      parameters:
        - in: query
          name: userId
          type: integer
          required: true
          description: ID de l'utilisateur
      responses:
        '200':
          description: Transactions récupérées avec succès
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Requête invalide
        '500':
          description: Erreur interne du serveur
  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Récupérer les détails d'une transaction spécifique
      description: API pour récupérer les détails d'une transaction en fonction de son ID
      parameters:
        - in: path
          name: transactionId
          type: integer
          required: true
          description: ID de la transaction
      responses:
        '200':
          description: Détails de la transaction récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetails'
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
    put:
      tags:
        - Transaction Module
      summary: Modifier les informations d'une transaction
      description: API pour modifier les informations d'une transaction existante
      parameters:
        - in: path
          name: transactionId
          type: integer
          required: true
          description: ID de la transaction
        - in: body
          name: body
          description: Payload pour modifier la transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: Transaction mise à jour avec succès
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Champs invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: integer
      accountId:
        type: integer
      date:
        type: string
        format: date
      amount:
        type: number
      description:
        type: string
  TransactionDetails:
    type: object
    properties:
      id:
        type: integer
      accountId:
        type: integer
      date:
        type: string
        format: date
      amount:
        type: number
      description:
        type: string
      category:
        type: string
      notes:
        type: string
  TransactionUpdate:
    type: object
    properties:
      amount:
        type: number
      description:
        type: string
      category:
        type: string
      notes:
        type: string
  ApiResponse:
    type: object
    properties:
      message:
        type: string
